add snippet.nvim support
davidgranstrom/scnvim pull request #139
Opened 2021-03-23 02:37 UTC by salkin-mada

1. 
Did use extra safety in `SCNvim.sc` -> `snippetFormat = snippetFormat ? "ultisnips";`
But really `util.vim` keeps check of this.

2.
Will add info about `vim.g.scnvim_snippet_format` in the wiki after merge.
Additionally mention the `vim.g.scdoc_render_prg` - i don't see it mentioned anywhere, but maybe i am mistaking.

PS. Not really sure about line `159` in `SCNvim.sc`, old line?

2021-03-23 09:06 UTC, madskjeldgaard commented
Amazing work. I can test this out

2021-03-23 11:12 UTC, davidgranstrom commented
@salkin-mada Thanks for this! I'll try and review this tonight.

> Did use extra safety in `SCNvim.sc` -> `snippetFormat = snippetFormat ? "ultisnips";`
> But really `util.vim` keeps check of this.
> 
> 
> Will add info about `vim.g.scnvim_snippet_format` in the wiki after merge.
> Additionally mention the `vim.g.scdoc_render_prg` - i don't see it mentioned anywhere, but maybe i am mistaking.

Please add a note about the new option in `doc/SCNvim.txt` with a description on what it does. I would maybe put it under the "Configuration" section among the "Extra" options. Also great if you could add it to the wiki of course!

> 
> PS. Not really sure about line `159` in `SCNvim.sc`, old line?

Can you send a link to the line in question here on github? I'm not sure either :)

2021-03-23 12:16 UTC, madskjeldgaard commented
This works really wonderfully!

I wonder if we could make scnvim add the path of the resulting snippets to the package path automatically as part of this? So that the user only needs to `require'scnvim_snippets'` to get the table.

2021-03-23 12:52 UTC, davidgranstrom commented
> This works really wonderfully!
> 
> I wonder if we could make scnvim add the path of the resulting snippets to the package path automatically as part of this? So that the user only needs to `require'scnvim_snippets'` to get the table.

Maybe we could add a function in `lua/scnvim/utils.lua` that reads the generated file and returns the table for convenience?

2021-03-23 14:04 UTC, salkin-mada commented
wiki [PR](https://github.com/davidgranstrom/scnvim-wiki/pull/1)

2021-03-23 14:05 UTC, salkin-mada commented
@madskjeldgaard @davidgranstrom nice idea.
would be great if the `scnvim_snippets.lua` would be automatically added to package.path.
will look into that.

2021-03-23 14:09 UTC, davidgranstrom commented
> @madskjeldgaard @davidgranstrom nice idea.
> would be great if the `scnvim_snippets.lua` would be automatically added to package.path.
> will look into that.

I don't think we should modify package.path unless necessary, but to add a function that returns the (snippet) table would probably be useful! I'm not a snippets.nvim user so maybe I don't fully understand all the details, how does the configuration work?

2021-03-23 14:09 UTC, madskjeldgaard commented
> @madskjeldgaard @davidgranstrom nice idea.
> would be great if the `scnvim_snippets.lua` would be automatically added to package.path.
> will look into that.

I tried messing around with it here and there is some complexity in it. If you are using scnvims root dir global var the package needs to be added after that var is populated. And then additionally the user can only require this module with the snippets AFTER scnvim has loaded. Hmm... maybe there should simply be an scnvim function one can call whenever and then that adds it to the package path and returns the module ? Just ideas....amaybe there's a cooler way of doing it

2021-03-23 14:15 UTC, salkin-mada commented
> Can you send a link to the line in question here on github? I'm not sure either :)
in PR feature branch:
https://github.com/salkin-mada/scnvim/blob/assets/scide_scnvim/Classes/SCNvim.sc#L159

and in the master here:
https://github.com/davidgranstrom/scnvim/blob/master/scide_scnvim/Classes/SCNvim.sc#L153

wouldn't it be cleaner to say:
```supercollider
// vim
snippet = "snippet %\n%\nendsnippet\n".format(snippetName, className ++ argList);
// lua
snippet = "['%'] = [[%]];\n".format(snippetName, className ++ argList);
```
or actually just create a new var. `snippetContent`
```
snippetContent = className ++ argList;
                        case
                        {snippetFormat == "ultisnips"} {
                            snippet = "snippet %\n%\nendsnippet\n".format(snippetName, snippetContent);
                        }
                        {snippetFormat == "snippets.nvim"} {
                            snippet = "['%'] = [[%]];\n".format(snippetName, snippetContent);
                        };
```

But again. This is silly details :) - i just stumbled upon that line a bit.
Now i see that's it a simple redefinition of the `snippet` var. No problem really.

2021-03-23 14:21 UTC, salkin-mada commented
> I don't think we should modify package.path unless necessary, but to add a function that returns the (snippet) table would probably be useful! I'm not a snippets.nvim user so maybe I don't fully understand all the details, how does the configuration work?

good point. I need to go AFK. Will return later with snippets.nvim config workings info. :)
But yes. `snippets.supercollider = X` really just need a lua table.

2021-03-23 14:57 UTC, madskjeldgaard commented
> > I don't think we should modify package.path unless necessary, but to add a function that returns the (snippet) table would probably be useful! I'm not a snippets.nvim user so maybe I don't fully understand all the details, how does the configuration work?
> 
> good point. I need to go AFK. Will return later with snippets.nvim config workings info. :)
> But yes. `snippets.supercollider = X` really just need a lua table.

good ideas!

2021-03-23 22:05 UTC, davidgranstrom requested changes

2021-03-24 09:32 UTC, salkin-mada commented on scide_scnvim/Classes/SCNvim.sc
> +            file.write("M = {" ++ Char.nl);
true. will go for a lowercase local then -> `local snippets = ...` and `return snippets`

2021-03-24 09:33 UTC, salkin-mada commented on scide_scnvim/Classes/SCNvim.sc
> +    *generateAssets {|rootDir, snippetFormat|
yep, kool. will add the changes now

2021-03-24 09:40 UTC, salkin-mada commented on autoload/scnvim/util.vim
> +function! scnvim#util#get_snippet_format() abort
sure. nice!

2021-03-24 10:05 UTC, salkin-mada reviewed
pushed changes.

2021-03-24 10:39 UTC, davidgranstrom reviewed
@salkin-mada Thanks, looks good!

2021-03-24 10:40 UTC, davidgranstrom approved these changes

2021-03-26 10:04 UTC, madskjeldgaard commented
If anyone was wondering how to use this PR with the lua-supercollider-snippets plugin, here is a temporary hack that I am sharing here in case anyone needs it :) 

```lua

local supercollider_snippets = require'supercollider-snippets'

local function append_scnvim_snippets(intable)
	local scnvim_snippet_path = "/home/mads/.local/share/nvim/plugged/scnvim/scnvim-data/scnvim_snippets.lua"
	local scnvimsnips = loadfile(scnvim_snippet_path)()
	for k,v in pairs(scnvimsnips) do
		intable[k] = v
	end

	return intable
end

append_scnvim_snippets(supercollider_snippets)

```

and then you can insert `supercollider_snippets` in the global snippets table

2021-03-26 11:21 UTC, davidgranstrom commented
@salkin-mada I wrote a small lua helper that returns the current snippet file (based on the format). I guess it is mostly useful for this particular case, because it will make it easy to assign the snippets for `snippets.nvim` to use, but I made it general enough so that it also possible to read the contents of supercollider.snippets and could be extended to more formats later on. Is it okay to push it to this branch or do you have something locally that you would like to push first?

2021-03-28 15:45 UTC, salkin-mada commented
@davidgranstrom sorry for the wait.
sounds good. push it.

2021-03-28 17:33 UTC, davidgranstrom commented
> @davidgranstrom sorry for the wait.
> sounds good. push it.

No worries. Pushed. Let me know if you think this will work for the `snippets.nvim` use case and I'll include it!

2021-03-31 12:15 UTC, davidgranstrom commented
> kool, looks fine.
> but could you show me how to use this function outside the scnvim dir.
> If I understand correctly this helper function returns either the string for ultisnips or the table for snippets.nvim? tried adding it to a util func `scnvim#utils#get_snippets` so i could call it via nvim call or vim.fn. But cant get it to return the table. please remind me / enlighten me on how this could be used. thanks

Sure! I was thinking something this might work (haven't had a chance to try `snippets.nvim` yet though..)

```lua
local scnvim_snippets = require'scnvim.util'.get_snippets()

if scnvim_snippets then
  -- snippets is pointing to snippets.nvim module
  snippets.supercollider = scnvim_snippets
end
```

2021-03-31 13:04 UTC, salkin-mada commented
in `lua` i would do something like
```lua
local scnvim_snippets = require'scnvim.util'.get_snippets()
for k,v in pairs(scnvim_snippets) do snippets.supercollider[k] = v end
```
but i cant get `scnvim.util` into my path it seems. my package path loader cant find the module.
first i thought i forgot to pull your commits :) but that wasnt it.

cant get it to work like i would with:
```lua
-- snippets.supercollider already holds my own snippets
package.path = package.path .. assert(";/home/salkin/kode/scnvim-fork/scnvim/scnvim-data/scnvim_snippets.lua")
for k,v in pairs(require'scnvim_snippets') do snippets.supercollider[k] = v end
```
or
```lua
local supercollider_snippets = require'my-own-supercollider-snippets'
local scnvim_snippets = loadfile(";/home/salkin/kode/scnvim-fork/scnvim/scnvim-data/scnvim_snippets.lua")()
local function add_scnvim_snippets(table)
	for k,v in pairs(scnvim_snippets) do
		table[k] = v
	end
	return table
end
	
add_scnvim_snippets(supercollider_snippets)
```

2021-03-31 17:16 UTC, salkin-mada commented
>  @madskjeldgaard
> 
> ... messing around with it here and there is some complexity in it. If you are using scnvims root dir global var the package needs to be added after that var is populated. And then additionally the user can only require this module with the snippets AFTER scnvim has loaded.  ...

My `invalid module`-trouble is probably a result of some init time thingy . Like the observations Mads was talking about.

2021-03-31 17:41 UTC, davidgranstrom commented
> > @madskjeldgaard
> > ... messing around with it here and there is some complexity in it. If you are using scnvims root dir global var the package needs to be added after that var is populated. And then additionally the user can only require this module with the snippets AFTER scnvim has loaded.  ...
> 
> My `invalid module`-trouble is probably a result of some init time thingy . Like the observations Mads was talking about.

Hmm, yes that seems to be the case. Good call @madskjeldgaard! I think the solution is to move the `get_scnvim_root_dir` function from installation to the other utilities so we can call that function instead. I'll let you know as soon as I've tried it out locally.

2021-03-31 17:48 UTC, davidgranstrom commented
@salkin-mada I moved the get_root_dir function to the other utilities, I think it should work as expected now.

2021-04-07 13:42 UTC, salkin-mada commented
@madskjeldgaard could you test this snippets.nvim convenience table getter? You are on `vim-plug` if i remember correctly.
I am starting to suspect my lua package/module init time issues is due to some `packer.nvim` thingy..
possibly a direct consequence is something as puzzling as this: #140 
see [comment](https://github.com/davidgranstrom/scnvim/pull/140#issuecomment-812844273)

2021-04-19 13:59 UTC, madskjeldgaard commented
I just tested the latest commits here and it seems to work nicely. I am now using the get_scnvim_root_dir() method to get the data and it works well ! 

Here's how I do it now for reference

```lua

local supercollider_snippets = require'supercollider-snippets'

local function append_scnvim_snippets(intable)
	local scnvim_snippet_path = require'scnvim/utils'.get_scnvim_root_dir() .. "/scnvim-data/scnvim_snippets.lua"
	local scnvimsnips = loadfile(scnvim_snippet_path)()
	for k,v in pairs(scnvimsnips) do
		intable[k] = v
	end

	return intable
end

append_scnvim_snippets(supercollider_snippets)
```

and then I put the `supercollider_snippets` variable in the snippets.nvim globa snippets l table.

2021-04-19 14:27 UTC, davidgranstrom commented
> I just tested the latest commits here and it seems to work nicely. I am now using the get_scnvim_root_dir() method to get the data and it works well !
> 
> Here's how I do it now for reference
> 
> ```lua
> local supercollider_snippets = require'supercollider-snippets'
> 
> local function append_scnvim_snippets(intable)
> 	local scnvim_snippet_path = require'scnvim/utils'.get_scnvim_root_dir() .. "/scnvim-data/scnvim_snippets.lua"
> 	local scnvimsnips = loadfile(scnvim_snippet_path)()
> 	for k,v in pairs(scnvimsnips) do
> 		intable[k] = v
> 	end
> 
> 	return intable
> end
> 
> append_scnvim_snippets(supercollider_snippets)
> ```
> 
> and then I put the `supercollider_snippets` variable in the snippets.nvim globa snippets l table.

@madskjeldgaard Thanks for the feedback! There is also a convenience function added for this purpose called `get_snippets()` (also in utils). I image something like this should work (your example but modified)

```lua
local function append_scnvim_snippets(intable)
  local scnvimsnips = require'scnvim/utils'.get_snippets()
  for k,v in pairs(scnvimsnips) do
    intable[k] = v
  end
  return intable
end
```

Does it still work if you exchange your function for this one?

2021-04-19 14:31 UTC, madskjeldgaard commented
> > I just tested the latest commits here and it seems to work nicely. I am now using the get_scnvim_root_dir() method to get the data and it works well !
> > Here's how I do it now for reference
> > ```lua
> > local supercollider_snippets = require'supercollider-snippets'
> > 
> > local function append_scnvim_snippets(intable)
> > 	local scnvim_snippet_path = require'scnvim/utils'.get_scnvim_root_dir() .. "/scnvim-data/scnvim_snippets.lua"
> > 	local scnvimsnips = loadfile(scnvim_snippet_path)()
> > 	for k,v in pairs(scnvimsnips) do
> > 		intable[k] = v
> > 	end
> > 
> > 	return intable
> > end
> > 
> > append_scnvim_snippets(supercollider_snippets)
> > ```
> > 
> > 
> > and then I put the `supercollider_snippets` variable in the snippets.nvim globa snippets l table.
> 
> @madskjeldgaard Thanks for the feedback! There is also a convenience function added for this purpose called `get_snippets()` (also in utils). I image something like this should work (your example but modified)
> 
> ```lua
> local function append_scnvim_snippets(intable)
>   local scnvimsnips = require'scnvim/utils'.get_snippets()
>   for k,v in pairs(scnvimsnips) do
>     intable[k] = v
>   end
>   return intable
> end
> ```
> 
> Does it still work if you exchange your function for this one?

Yep this works nicely! Thanks! IMO this PR is good now :)

2021-04-19 17:33 UTC, davidgranstrom commented
@salkin-mada Thanks! Merging this now.

2021-04-19 17:33 UTC, merged

2021-04-19 18:09 UTC, salkin-mada commented
🎉