fix for method documentation search
davidgranstrom/scnvim pull request #233
Opened 2024-03-16 05:48 UTC by sadguitarius

When searching for documentation on a method, the regex doesn't find cases where the line starts with the class name and not just the method name. Also Windows path names are broken coming out of the quickfix window.

This PR should hopefully provide a fix. I added a check for whether Neovim is running on Windows before messing with backslashes, so the path fix shouldn't affect anything on Mac or Linux. Let me know if you need me to split this into a separate commit, I thought I'd just sneak this in since it's just a tiny change.

When you get a chance, can you check this and let me know if anything needs to be cleaned up? I restructured the on_open method and quickfix logic a little so the regex would be easier to parse. I don't think this will break anything, but let me know if I'm missing something and there's a better way to do it. Thanks!

2024-03-19 08:59 UTC, davidgranstrom commented
Thank you for your PR, I'll try to review this as soon as possible!

An initial thought is that you could use the pre-computed value for the `isWindows` check, you will find it in the `scnvim.path` module.

2024-03-19 15:16 UTC, sadguitarius commented
Ah I missed that function! Thought I'd done a proper search for something like that but apparently not. I swapped my function out for that one.

2024-04-05 18:38 UTC, sadguitarius commented
Cool! I don't see anything showing up in reviews, but it's possible I'm looking in the wrong place.

2024-04-05 20:53 UTC, davidgranstrom requested changes

2024-04-05 20:54 UTC, davidgranstrom commented
Sorry, I had forgotten to submit the review!

2024-04-09 06:29 UTC, sadguitarius commented on lua/scnvim/help.lua
> +M.on_open = action.new(function(err, uri, subject, method)
Ok your suggestion to use fnamemodify makes it easy to get things done without changing the method (my nvim api knowledge is thin).

2024-04-09 06:29 UTC, sadguitarius commented on lua/scnvim/help.lua
> +    local cmd = string.format('SCNvim.getFileNameFromUri("%s")', uri)
Nice!

2024-04-09 06:44 UTC, sadguitarius commented on lua/scnvim/help.lua
> -          pattern = string.format('^\\.%s', name),
Hmm, I just tried debugging and when I inspect `item.pattern` it shows up blank, and `item.text` gives me the method name. I'm not too familiar with the inner workings of the quickfix list, just kludging away until I get the desired results. Any suggestions?

2024-04-09 06:46 UTC, sadguitarius commented
Ok I have a good head start on these changes and things seem to be working fine. Check my comment re: the quickfix list when you can, I'm not sure how best to implement your suggestion there. Thanks!

2024-04-15 15:15 UTC, davidgranstrom commented
The new changes looks good to me! But there seems to be a regression from the last commit, when I search for method such as `tanh` and try to open `Classes/SequenceableCollection .tanh` the pattern matching  end up on word `SequenceableCollection` rather than `.tanh` (which is further down that particular help file).

I haven't found a good answer to the `pattern` vs. `text` discussion earlier, so let's use `text` for now as it seems to be working on your end.

2024-04-18 18:37 UTC, sadguitarius commented
I just fixed a wrong signature that was causing the method to fail. Should be ok now!

2024-04-19 09:08 UTC, davidgranstrom approved these changes

2024-04-19 09:13 UTC, davidgranstrom commented
Thanks!

2024-04-19 09:15 UTC, merged